#!/usr/bin/env python3
"""Generate syscall name/arity tables from a strace source checkout.

Usage: gen_syscall_tables.py /path/to/strace src/syscall_tables_generated.c
The generated data is factual ABI metadata; no strace decoder code is copied.
"""

import re
import sys
from pathlib import Path

LINE = re.compile(
    r"\[\s*(?:(?:BASE_NR\s*\+\s*)?([0-9]+))\s*\]\s*=\s*"
    r"\{\s*([0-9]+)\s*,.*?\"([^\"]+)\""
)


def parse(path: Path):
    out = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        m = LINE.search(line)
        if m:
            out[int(m.group(1))] = (m.group(3), int(m.group(2)))
    return out


def table_size():
    header = Path(__file__).resolve().parents[1] / "include/syscall_parser.h"
    match = re.search(r"^#define\s+SYSCALL_TABLE_SIZE\s+(\d+)u?\b", header.read_text(), re.M)
    if not match:
        raise ValueError("SYSCALL_TABLE_SIZE missing in syscall_parser.h")
    return int(match.group(1))


def emit_array(f, symbol, entries, abi_bits, count):
    if any(n >= count for n in entries):
        raise ValueError("strace syscall number exceeds SYSCALL_TABLE_SIZE; update syscall_parser.h")
    f.write(f"const syscall_entry_t {symbol}[SYSCALL_TABLE_SIZE] = {{\n")
    for nr in range(count):
        if nr in entries:
            name, nargs = entries[nr]
            f.write(f'    [{nr}] = {{ "{name}", {nargs}, {abi_bits}, 0 }},\n')
        else:
            f.write(f'    [{nr}] = {{ NULL, 6, {abi_bits}, 0 }},\n')
    f.write("};\n\n")


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    root = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    common = parse(root / "src/linux/generic/syscallent-common.h")
    common32 = parse(root / "src/linux/32/syscallent-common-32.h")
    arm64 = parse(root / "src/linux/64/syscallent.h")
    arm = parse(root / "src/linux/arm/syscallent.h")
    arm64.update(common)
    arm.update(common32)
    arm.update(common)
    count = table_size()
    if max(arm64.keys() | arm.keys()) + 1 != count:
        raise ValueError("SYSCALL_TABLE_SIZE must equal the largest known syscall number plus one")

    with out_path.open("w", encoding="utf-8") as f:
        f.write("/* Generated by tools/gen_syscall_tables.py. */\n")
        f.write('#include <stddef.h>\n#include "syscall_parser.h"\n\n')
        emit_array(f, "syscall_tables_64", arm64, 64, count)
        emit_array(f, "syscall_tables_32", arm, 32, count)


if __name__ == "__main__":
    main()
